version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: quizapi_user
      POSTGRES_PASSWORD: quizapi_password
      POSTGRES_DB: quizapi_db
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  postgrest:
    image: postgrest/postgrest:latest
    container_name: postgrest
    environment:
      PGRST_DB_URI: postgres://quizapi_user:quizapi_password@db:5432/quizapi_db
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: quizapi_user
    depends_on:
      - db
    ports:
      - "3000:3000"

# volumes:
#   db_data: