FROM node:18-alpine AS deps
WORKDIR /app
# Utiliser le package.json du dossier quiz-frontend
COPY quiz-frontend/package.json ./
RUN npm install

FROM node:18-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY quiz-frontend/ .
RUN npm run build

FROM node:18-alpine AS runner
WORKDIR /app
ENV NODE_ENV development

# Copier node_modules nécessaires
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next

EXPOSE 3000
ENV PORT 3000

# Utiliser npm run dev pour le développement
CMD ["npm", "run", "dev"]