services:
  frontend:
    build:
      context: ./app
      dockerfile: ../Dockerfile
    container_name: quiz-frontend
    ports:
      - "3001:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    command: npm run dev
    networks:
      - quizapi-network

networks:
  quizapi-network:
    external: true
